- go.mod
- go.sum
- yaml/build_test.go
- yaml/stage.go
- yaml/stage_test.go
- yaml/testdata/build_anchor_stage.yml
- yaml/testdata/build_anchor_step.yml
Directly in relation to:
https://github.com/go-yaml/yaml/issues/184
The solution to use [buildkite/yaml](https://github.com/buildkite/yaml) is [documented in the thread](https://github.com/go-yaml/yaml/issues/184#issuecomment-439254361).
**NOTE:**
We vendor directly from the commit:
([`0caa5f0796e36057e59d6782832a9c774f457842`](https://github.com/buildkite/yaml/commit/0caa5f0796e36057e59d6782832a9c774f457842))
rather then the release:
([`v2.2.0`](https://github.com/buildkite/yaml/releases/tag/v2.2.0))
because of a Go module versioning issue:
https://github.com/golang/go/wiki/Modules#semantic-import-versioning
> If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module …
> Use buildkite/yaml to enable anchors in stages

- constants/badge.go
> feat(badges): add build status badge constants

- library/log.go
- library/log_test.go
This is intended to help improve where we're attempting to append logs to an existing log entry.
I believe this will help with code maintainability, code readability as well as reduce lines of code 👍 
[Here is an example](https://github.com/go-vela/pkg-executor/blob/be67a37fccbb68b660084a69961bc230e3c8e8e5/executor/linux/build.go#L227-L234) of the code we use to accomplish this:
```go
// TODO: remove hardcoded reference
// update the init log with progress
l.SetData(
append(
l.GetData(),
[]byte(fmt.Sprintf("  $ docker image inspect %s\n", s.Image))...,
),
)
```
> feat(library): add AppendData() for Log

- yaml/stage.go
- yaml/stage_test.go
I should have completed this when I first added the `Done` channel to stages:
https://github.com/go-vela/types/pull/41
Unfortunately, I missed it so that's why I added a `bug` label.
> fix(yaml): create done channel for stages

- constants/secret.go
- go.mod
- go.sum
- library/secret.go
- library/secret_test.go
This change is to address when a user tries to view secret values via the API ( [GetSecrets](https://github.com/go-vela/server/blob/master/api/secret.go#L156) and[GetSecrets](https://github.com/go-vela/server/blob/master/api/secret.go#L191) ).
The value is when a user view's their secret they don't see `null` in place of the value. The mask is designed to communicate to the user that the API will not return secret values.
> feat: add masked value when sanitizing secrets

- pipeline/ruleset.go
- pipeline/ruleset_test.go
This change allows the `status:` YAML tag in a ruleset to be treated as a no-op.
There was a big discovered when a user passed a pipeline:
```yaml
ruleset:
status: [ success, failure ]
```
When this was compiled the ruleset was removed because at compile time the build status is always pending.
> fix: update status to be an no-op

- library/build.go
- library/build_test.go
- library/repo.go
- library/repo_test.go
- library/service.go
- library/service_test.go
- library/step.go
- library/step_test.go
- library/user.go
- library/user_test.go
I noticed our [`environment()`](https://github.com/go-vela/compiler/blob/master/compiler/native/environment.go#L71-L149) function in the [go-vela/compiler](https://github.com/go-vela/compiler) is quite lengthy and difficult to digest:
```go
// helper function that creates the standard set of environment variables for a pipeline.
func environment(b *library.Build, m *types.Metadata, r *library.Repo, u *library.User) map[string]string {
workspace := fmt.Sprintf("/home/%s/%s", r.GetOrg(), r.GetName())
env := map[string]string{
// build specific environment variables
"BUILD_AUTHOR":       b.GetAuthor(),
"BUILD_AUTHOR_EMAIL": b.GetEmail(),
"BUILD_BRANCH":       b.GetBranch(),
"BUILD_CHANNEL":      "TODO",
"BUILD_COMMIT":       b.GetCommit(),
"BUILD_CREATED":      unmarshal(b.GetCreated()), …
```
> feat(library): add Environment() functions

- library/build_test.go
- library/context_test.go
- library/executor_test.go
- library/hook_test.go
- library/log_test.go
- library/login_test.go
- library/repo_test.go
- library/secret_test.go
- library/service_test.go
- library/step_test.go
- library/string_test.go
- library/user_test.go
This will refactor all tests in the `go-vela/types/library` package to use table tests.
More information: https://github.com/golang/go/wiki/TableDrivenTests
I was able to cut the total number lines of code for our tests in half 🎉
> test(library): refactor for table tests

- database/build_test.go
- database/context_test.go
- database/hook_test.go
- database/log_test.go
- database/repo_test.go
- database/secret_test.go
- database/service_test.go
- database/step_test.go
- database/user_test.go
This will refactor all tests in the `go-vela/types/database` package to use table tests.
More information: https://github.com/golang/go/wiki/TableDrivenTests
I was able to significantly reduce the total number lines of code for our tests 🎉
> test(database): refactor for table tests

- raw/map_test.go
- raw/slice_test.go
This will refactor all tests in the `go-vela/types/raw` package to use table tests.
More information: https://github.com/golang/go/wiki/TableDrivenTests
> test(raw): refactor for table tests

- yaml/build_test.go
- yaml/metadata_test.go
- yaml/ruleset_test.go
- yaml/secret_test.go
- yaml/service_test.go
- yaml/stage_test.go
- yaml/step_test.go
- yaml/template_test.go
- yaml/testdata/ruleset_simple.yml
- yaml/ulimit_test.go
- yaml/volume_test.go
- yaml/worker_test.go
This will refactor all tests in the `go-vela/types/yaml` package to use table tests.
More information: https://github.com/golang/go/wiki/TableDrivenTests
> test(yaml): refactor for table tests

- library/build.go
- library/hook.go
- library/log.go
- library/login.go
- library/repo.go
- library/secret.go
- library/service.go
- library/step.go
- library/user.go
Adding swagger model definitions to types used in endpoints defined in [go-vela/server](https://github.com/go-vela/server)
> feat(open-api): add open api (swagger) definitions to models

- pipeline/ruleset.go
- pipeline/ruleset_test.go
- yaml/ruleset_test.go
- yaml/testdata/ruleset_regex.yml
Current ruleset matching utilizes a file match pattern utility. This does not allow for more stringent matching, particularly with version tags. Use regex pattern matching since it allows for greater control and it commonly known.
> Issue #70: Allow greater fidelity of ruleset matching

- constants/limit.go
- database/user.go
- database/user_test.go
adding logic to adhere to the hard limit imposed by the database of `VARCHAR(5000)`
this logic assumes that postgres does not pad values when inserting `[]string` arrays, will do some more research
> fix(user): implement hard limit on user favorites

- webhook.go
- webhook_test.go
pre-work for https://github.com/go-vela/community/issues/66 and https://github.com/go-vela/community/issues/70
will be functional once associated, incoming PR to server is merged (https://github.com/go-vela/server/pull/169)
- adds method on Webhook struct called `ShouldSkip`
- adds helper function to check string for skip directive
- adds tests to check `ShouldSkip` functionality
> feat(skip): add ability to skip hook

- constants/matcher.go
- constants/operator.go
- pipeline/ruleset.go
- pipeline/ruleset_test.go
- yaml/build_test.go
- yaml/ruleset.go
- yaml/ruleset_test.go
- yaml/testdata/ruleset_advanced.yml
This PR is part of the effort for https://github.com/go-vela/community/issues/12
It adds a `matcher` field to the `ruleset` struct. The default for this field will be `filepath`.
**NOTE: The `matcher` field is not required to be provided to maintain backwards compatibility.**
As an example:
```yaml
steps:
- name: foo
image: alpine:latest
pull: true
ruleset:
tag: "^refs/tags/(\\d+\\.)+\\d+$"
matcher: regexp
```
Tests have been added to account for this new change.
> feat: enable pattern matcher for ruleset

- pipeline/secret.go
- pipeline/secret_test.go
This PR will help fix a bug in the executor that is stopping us from using the proper key when querying for a secret.
Executor PR:
https://github.com/go-vela/pkg-executor/pull/45
> fix(secrets): convert valid to parse functions

- pipeline/container.go
- pipeline/container_test.go
**EDIT:**
I figured out why I saw this behavior 👍 
I had a corrupted version of the `go-vela/compiler` repo cached in my local stack that I was running for the `go-vela/server`.
This corrupted cache caused the `go-vela/types/pipeline/secret.Origin.Container` field to be `nil` rather than the expected `Container{}` it should be.
**END EDIT**
This PR will make the `go-vela/types/pipeline/container.Empty()` function return true if the underlying container being provided is `nil`.
I ran into this issue when running some pipelines locally today 😢 
I'm not entirely sure how or why I'm seeing this stack trace so I'll have to do more digging to understand the underlying issue.
The error I'm presented with is:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal …
```
> fix(pipeline): handle nil container for Empty()

- database/build.go
- database/build_test.go
- library/build.go
- library/build_test.go
Adds the `VELA_PULL_REQUEST_SOURCE` and `VELA_PULL_REQUEST_TARGET` variables that match the base and head refs from [go-github](https://github.com/google/go-github/blob/master/github/pulls.go#L72-L73). 
Starts the work to complete https://github.com/go-vela/community/issues/28.
Allows plugins/users to determine both branches involved in a given pull request.
Note: The failing reviewdog action is unrelated to my changes.
> feat(build): track head and base ref for pr

- pipeline/secret.go
- pipeline/secret_test.go
Removing a check that is forcing shared secrets to be in the same org as the repo that is running.
The executor will also be updated where the function is being used:
https://github.com/go-vela/pkg-executor/blob/master/executor/linux/secret.go#L311-L324
> fix: shared secrets can be in any org

- library/build.go
- library/build_test.go
Update the `build.Environment` function in preparation of utilizing it within the [environment](https://github.com/go-vela/compiler/blob/master/compiler/native/environment.go#L165) function of the compiler repo.
> feat(build): update env to match compiler

- library/build.go
- library/build_test.go
Needed to remove redundancy of https://github.com/go-vela/compiler/pull/80/files#diff-aaaa6f887aabe33da42651528fd46e70R217-R218.
> feat(build): add channel var to Environment function

- pipeline/container.go
- pipeline/container_test.go
This PR adds support for a build with a `running` status to the `go-vela/types/pipeline/container.Execute()` function.
This allows us to make a more accurate decision if a container should be executed or not based off the current build status 👍 
Tests have been added to ensure backwards compatibility with the existing logic, as well as, verify the new behavior.
> enhance(pipeline): support running builds for container.Execute()

- cmd/schema/main.go
- yaml/build.go
- yaml/ruleset.go
- yaml/stage.go
- yaml/step.go
- yaml/template.go
- yaml/worker.go
main reason for the change is that the schema mistakenly showed steps that used `name` + `template` fields as invalid. we're now using `oneof_required` schema tags to help with that and retrofitted `steps` and `stages` at the root level with the same.
other changes:
- minor refactor for consistency
- wrap volume override in check to make sure it exists
- mark missed required fields as `required`
- improve some doc links in jsonschema tags
> fix(schema): check for image or template on step

- pipeline/container.go
- pipeline/container_test.go
Intended to fix:
https://github.com/go-vela/community/issues/108
> fix: skip path rule for container.Execute()

- yaml/stage.go
name is set to key if not supplied as evidenced by: https://github.com/go-vela/types/blob/master/yaml/stage.go#L78
> fix(schema): stages don't require name field

- database/worker.go
- database/worker_test.go
- library/worker.go
- library/worker_test.go
change to make the LastCheckedIn type more similar to build's [enqueued field](https://github.com/go-vela/types/blob/f1af1d59136e3be6a6126870779b42c212ce3565/database/build.go#L33)
> fix: change worker lastCheckedIn to type int64

- yaml/secret.go
- yaml/secret_test.go
- yaml/testdata/step_secret_slice_invalid_no_source.yml
- yaml/testdata/step_secret_slice_invalid_no_target.yml
When using the method to inject a secret with alternative name, ie.
```
secrets:
- source: secret
target: alt_secret
```
it's possible to expose the secret by doing the following:
```
secrets:
- source: secret
- target: alt_secret
```
> fix: issue with accidental secret exposure via wrong syntax

- version/doc.go
- version/metadata.go
- version/metadata_test.go
- version/version.go
- version/version_test.go
Implementing a custom `Version` type for Vela that can be referenced throughout the different repos.
When rendered as JSON the output looks like:
```json
{
"canonical": "v1.2.3",
"major": 1,
"minor": 2,
"patch": 3,
"metadata": {
"architecture": "amd64",
"build_date": "1970-1-1T00:00:00Z",
"compiler": "gc",
"git_commit": "abcdef123456789",
"go_version": "1.15.0",
"operating_system": "linux"
}
}
```
Beyond the `String()` functions, this package also supports two different functions:
* `Meta()` - returns only the metadata surrounding the version of the application
* `Semantic()` - returns only the canonical semantic version of the application
> feat: add version pkg for Vela

- library/template.go
- library/template_test.go
- yaml/template.go
- yaml/template_test.go
Changes:
- Adding Template library type for use with `pipelines/*/*/templates` referenced in the pipeline endpoints feature https://github.com/go-vela/server/pull/203
- Moving map helper to yaml Template type (duplicate code used in server AND compiler) 
Why?
- YAML Template type exists here https://github.com/go-vela/types/blob/master/yaml/template.go#L15-L19 but lacks a field for HTMLURL that would greatly improve the functionality provided by`pipelines/*/*/templates`. Namely, providing the HTMLURL will allow for direct-linking to templates in the UI.
- mapFromTemplates exists in the compiler but is now being duplicated in https://github.com/go-vela/server/pull/203
https://github.com/go-vela/compiler/blob/cd7849cddf72ecd91e092ca050d7dd71d6c30f73/compiler/native/expand.go#L92-L101 this …
> feat: add template to library, add map helper from compiler

- constants/limit.go
* this allows for a build timeout of as low as 1 minute to be set in cli, ui, etc.
* corresponding ui pr: https://github.com/go-vela/ui/pull/240
> feat(repo settings): allow minimum build timeout of 1 minute

- database/worker.go
- database/worker_test.go
- library/worker.go
- library/worker_test.go
Add the `build_limit` field to the Worker struct to allow tracking the [BUILD_LIMIT](https://github.com/go-vela/worker/blob/7e41a9d30647af09eab67e97c6ada259e4f0b3f2/cmd/vela-worker/flags.go#L48) for all workers.
xref: https://github.com/go-vela/community/issues/164
> enhance(workers): add build_limit field

- constants/driver.go
Part of the effort for https://github.com/go-vela/community/issues/54
This adds an executor driver for the `local` executor to our list of constants.
I also renamed any references to `agent` to the proper term of `worker`.
> feat(constants): add local executor driver

- yaml/ruleset.go
Updates the `Rules` struct to render the keys with `[]` syntax instead of across multiple lines with `-`. 
The current behavior of this package when utilizing `yaml.Marshal`:
```yaml
events:
- push
- tag
```
The updated behavior of this package when utilizing `yaml.Marshal`:
```yaml
events: [ push, tag ]
````
I created a brief example [here](https://play.golang.org/p/ROz6_kjcpFr) to help visualize the difference when utilizing the `flow` flag.
> enhance(yaml): utilize flow to render brackets with yaml.Marshal

- library/service.go
- library/service_test.go
- library/step.go
- library/step_test.go
Part of the effort for https://github.com/go-vela/community/issues/54
This adds functions for converting a `go-vela/types/pipeline.Container` type to a `go-vela/types/library` type:
* [ServiceFromContainer()](https://github.com/go-vela/types/blob/feature/library/from_container/library/service.go#L480-L591)
* [StepFromContainer()](https://github.com/go-vela/types/blob/feature/library/from_container/library/step.go#L509-L627)
This will be used throughout the [go-vela/pkg-executor](https://github.com/go-vela/pkg-executor) repo.
> feat(library): enable creating resources from container

- go.mod
- go.sum
- pipeline/container.go
- pipeline/container_test.go
Part of the effort for https://github.com/go-vela/community/issues/54
This adds functions for substituting `${VAR}` and `$${VAR}` declarations for the `go-vela/types/pipeline.Container` type:
* [Substitute()](https://github.com/go-vela/types/blob/feature/pipeline/container_substitute/pipeline/container.go#L244-L302)
This will be used throughout the [go-vela/pkg-executor](https://github.com/go-vela/pkg-executor) repo.
Also, in this PR is moving the `Sanitize()` function for the container type to where the other container functions are located.
> feat(pipeline): add container substitute function

- version/version.go
this is needed so we can upgrade the semver package on other repos, otherwise you get this error when trying to upgrade to `semver/v3`:
```
version/version.go:42:3: cannot use v.Major() (type uint64) as type int64 in field value
version/version.go:43:3: cannot use v.Minor() (type uint64) as type int64 in field value
version/version.go:44:3: cannot use v.Patch() (type uint64) as type int64 in field value
```
> fix(version): fix to upgrade semver package

- constants/workspace.go
Part of the effort for https://github.com/go-vela/community/issues/54
This adds constants for setting up the default workspace path and default mount path for services and steps:
https://github.com/go-vela/types/blob/795d689a3f11d97eff2a89e1f1f0d9da6e8b02f1/constants/workspace.go#L9-L10
https://github.com/go-vela/types/blob/795d689a3f11d97eff2a89e1f1f0d9da6e8b02f1/constants/workspace.go#L12-L13
These constants will be used throughout several codebases like:
* [go-vela/cli](https://github.com/go-vela/cli/blob/feature/action/pipeline/exec/action/pipeline/exec.go#L57)
* [go-vela/compiler](https://github.com/go-vela/compiler/blob/master/compiler/native/environment.go#L185)
* [go-vela/pkg-executor](https://github.com/go-vela/pkg-executor/blob/feature/internal/step_environment/internal/step/envi …
> feat: add workspace constants for services and steps

- yaml/template.go
currently, the schema will mark a pipeline as invalid if you are defining `go` as the template format, eg. (taken from https://go-vela.github.io/docs/templates/):
```yaml
templates:
- name: go
source: github.com/octocat/hello-world/.vela/build.yml
format: go
type: github
```
This is, in fact, a valid option.
> fix(schema): add 'go' as enum for template format

- constants/compress.go
- constants/compression.go
- database/log.go
- database/log_test.go
Based off of https://github.com/go-vela/types/pull/154
Related to https://github.com/go-vela/server/pull/297
This enables us to pass an `int` (compression level) to the `go-vela/types/database.Log.Compress()` function.
The intention is to set the compression level as a flag on the server which will be passed to this function.
This also has an added benefit of being able to "turn off" log compression by passing a compression level of `0`.
Also added constants for all the supported compression levels:
* `CompressionNegOne`: `-1`
* `CompressionZero`: `0` - NOTE: This disables compression i.e. log data will not be compressed
* `CompressionOne`: `1`
* `CompressionTwo`: `2`
* `CompressionThree`: `3`
* `CompressionFour`: `4`
* `CompressionFive`: `5`
* `CompressionSix`: `6`
* `CompressionSeven`: …
> enhance(database): support setting different compression level

- .github/workflows/codeql-analysis.yml
- yaml/build_test.go
- yaml/stage.go
- yaml/stage_test.go
fixes the scenario where a user has multiple stages, the first stage is skipped, and the following stage(s) are executed before the `clone` stage can complete.
This bug is a race condition between the platform finishing `clone` and executing a continued stage.
For example, the following yaml will sometimes execute `second_stage-second_step` before clone can complete. 
Because the first stage is skipped, and the second stage provides a `needs` block, `clone` will not be added as a dependency. This code fixes that.
```yaml
version: "1"
stages:
first_stage:
steps:
- name: first_step
ruleset:
event: pull_request
image: golang
commands:
- echo "hello"
second_stage:
needs: [ first_stage ]
steps:
- name: second_step
ruleset:
event: push
image: golang
commands:
- echo "hello"
```
related worker …
> fix: add clone to needs if not present

- database/secret.go
- database/secret_test.go
- go.sum
This adds a `Encrypt()` and `Decrypt()` function for the `go-vela/types/database.Secret` type:
* [Encrypt()](https://github.com/go-vela/types/blob/feature/database/secret_encryption/database/secret.go#L122-L164)
* [Decrypt()](https://github.com/go-vela/types/blob/feature/database/secret_encryption/database/secret.go#L64-L120)
We've decided to use the Advanced Encryption Standard (`AES`) with a `256` bit key (a.k.a. `AES-256`):
https://en.wikipedia.org/wiki/Advanced_Encryption_Standard
We chose to use the [crypto](https://golang.org/pkg/crypto/) standard Golang library along with the various subpackages in it to accomplish this:
https://github.com/go-vela/types/blob/10b29a8edc965ff100f8e35519c85b8b218724af/database/secret.go#L8-L10
> NOTE: This functionality won't be added to Vela until …
> feat(database): add secret Encrypt() and Decrypt()

- database/encrypt.go
- database/encrypt_test.go
- database/repo.go
- database/repo_test.go
- database/secret.go
- database/secret_test.go
- database/user.go
- database/user_test.go
This adds some helper functions for encrypting and decrypting values in the `go-vela/types/database` package:
* [decrypt()](https://github.com/go-vela/types/blob/refactor/database/encryption_functions/database/encrypt.go#L15-L58)
* [encrypt()](https://github.com/go-vela/types/blob/refactor/database/encryption_functions/database/encrypt.go#L60-L98)
Also updated the types performing encryption to call these helper functions:
* [repo.Decrypt()](https://github.com/go-vela/types/blob/refactor/database/encryption_functions/database/repo.go#L64-L88)
* [repo.Encrypt()](https://github.com/go-vela/types/blob/refactor/database/encryption_functions/database/repo.go#L90-L109)
* [secret.Decrypt()](https://github.com/go-vela/types/blob/refactor/database/encryption_functions/database/secret.go#L59-L83)
* …
> refactor(database): use encrypt() and decrypt() helpers

- database/build_queue.go
- database/build_queue_test.go
- library/build_queue.go
- library/build_queue_test.go
- library/template.go
Based off of https://github.com/go-vela/sdk-go/pull/97#pullrequestreview-625404169
Related to https://github.com/go-vela/server/pull/299, https://github.com/go-vela/sdk-go/pull/97 and https://github.com/go-vela/mock/pull/107
This adds a `BuildQueue{}` type to the `github.com/go-vela/types/database` package:
https://github.com/go-vela/types/blob/63af263fc0b0710d45c31cc345a968c2915ea405/database/build_queue.go#L13-L19
This also adds a `BuildQueue{}` type to the `github.com/go-vela/types/library` package:
https://github.com/go-vela/types/blob/63af263fc0b0710d45c31cc345a968c2915ea405/library/build_queue.go#L9-L17
> feat(buildqueue): add build queue database and library types

- library/repo.go
- pipeline/container.go
- pipeline/container_test.go
Part of https://github.com/go-vela/community/issues/118
This PR updates the `go-vela/types/pipeline/Execute()` to enable the worker to skip evaluation of the comment in a ruleset, as it does not have awareness of that field. The server will already determine if the step should be run.
https://github.com/go-vela/types/blob/03af8e851d87933bc28764dcc82ea3188cdbbb59/pipeline/container.go#L163-L174
With this fix, the pipeline below helps illustrate when a comment step will run and not:
```yaml
version: "1"
steps:
- name: always run
image: alpine:latest
commands:
- echo "hi"
- name: only run when not a comment event
image: alpine:latest
commands:
- echo "hi"
ruleset:
event: [push, pull_request, tag, deploy]
- name: only run when a comment event and run vela in pr comment
image: alpine:latest …
```
> fix(comment): skip worker from evaluating comment for comment events

- database/build.go
- database/secret.go
- database/user.go
- database/worker.go
Part of the effort for https://github.com/go-vela/community/issues/248
This enables us to use the following custom data types with the `gorm.io/gorm` (V2 of GORM) package:
* `github.com/go-vela/types/raw.StringSliceMap`
* `github.com/lib/pq.StringArray{}`
Currently when attempting to store a `Build{}`, `Secret{}`, `User{}` or `Worker{}` in the database, you'll see an error like:
```
[error] unsupported data type: &[]
```
This error is returned because GORM is unsure what the underlying data types should be in the database for these.
In order to resolve this, we have to explicitly tell GORM what data types to use so it can store them in the database.
The official GORM documentation on this can be found here:
https://gorm.io/docs/data_types.html
There was also an issue posted on this …
> feat(database): use struct tags for custom types in gorm

- yaml/secret.go
- yaml/testdata/secret.yml
PR includes the following changes:
- add a check to skips secrets that have empty names
Details:
In certain, situations the compiler can call the marshaller; sometimes when this happens with templates the secrets being passed has a secret array that contains empty secret elements. This change adds extra checking in cases a secret element exists within the secrets block that doesn't have `name:`.
> fix: use tmp for empty name check

- library/build.go
- library/build_test.go
This updates the `github.com/go-vela/types/library.Build.Environment()` function for the `deployment` event.
This change will ensure that if a `deployment` is created from a tag on a repo:
```sh
vela add deployment --org myOrg --repo myRepo --ref refs/tags/v0.1.0
```
That the `BUILD_TAG` and `VELA_BUILD_TAG` environment variables will be set for that build.
This is accomplished by checking if the `ref` for the build object contains the prefix `refs/tags/`.
> enhance(build): set tag env vars for deployments

- pipeline/container.go
- pipeline/container_test.go
This updates the `github.com/go-vela/types/pipeline.Container.Sanitize()` function.
This change will ensure that if a `service` or `step` contains a slash (`/`) in the name, Vela can support it.
This is accomplished by checking if container has a slash in the name, and if so, replacing it with a dash (`-`).
This is similar logic to how we handle other special characters such as spaces (` `), periods (`.`) or underscores (`_`).
> enhance(container): support slash (/) in names

- yaml/service.go
completes go-vela/community/issues/267
pkg-runtime already has the ability to set ulimits for steps, this PR enables the compiler to set ulimits for services.
> feat: enable setting ulimits for services

- Makefile
looks like with https://github.com/go-vela/types/releases/tag/v0.9.0-rc2 the schema was not getting bundled with the release anymore. this is a quick fix for that. we might consider a submodule maybe?
> chore: fix schema generation

- pipeline/secret.go
fixes https://github.com/go-vela/community/issues/387
When we call `.ParseOrg`, we pass in the current repo's information (eg. https://github.com/go-vela/pkg-executor/blob/57b690402cf77554746eebe9e870ae7a3ec1e37d/executor/linux/secret.go#L196 - passing in current repo's org).
When a user provides a secret from a different org via the `key` property, the error prints the current org the user is trying to use the secret from instead of the org that they are referencing in the `key`.
for example:
Assuming the following pipeline is used in `github.com/go-vela/test`:
```yaml
version: "1"
steps:
- name: test
image: alpine:latest
pull: true
command:
- echo hi
secrets:
- name: org-secret
key: wass3r/secret
type: org
engine: native
```
The error would print:
```
error:invalid organization in key: …
```
> fix: reference correct secret parts in errors

- pipeline/container.go
- yaml/service.go
- yaml/step.go
Need for https://github.com/go-vela/community/issues/344.
> enhance(container): enable setting user

- version/version.go
part of https://github.com/go-vela/community/issues/432
`Version` is a payload expected for the `<api-url>/version` endpoint.
> fix: annotate payload for swagger

- .golangci.yml
- pipeline/secret.go
- raw/map.go
- yaml/ulimit.go
- yaml/volume.go
Made some changes to disable the magic number rule from the golangci linter. While working on attempting to address all the instances of the rule being broken, I noticed that there were several instances of the rule being manually disabled. I would love some feedback and conversation to make sure this would be a change worth making. Thanks!
> chore(linter): remove magic number rule

- library/step.go
- library/step_test.go
Both the local and linux executors have to init a step object in a couple of places. This moves that logic into `library` to facilitate reuse.
The executor can't use `StepFromContainer` because that relies on the container Environment which is not configured yet.  So, we rename `StepFromContainer` to `StepFromContainerEnvironment` to more accurately represent what it does. Then we add a new `StepFromBuildContainer` function to create a new Step and initialize it using data from a `library.Build` and a `pipeline.Container`.
For background, see the conversation here: https://github.com/go-vela/pkg-executor/pull/179#discussion_r735875710
This should be merged before https://github.com/go-vela/worker/pull/239
> fix: move Step init logic from executor to library

- constants/secret.go
[Related Issue](https://github.com/go-vela/community/issues/136)
Jenkins and Drone both manage to mask secrets in their logs using the mask `***`. I understand there may be concern of redundancy with the `SecretMask` constant, so I'm open to discussion on whether we should use that instead. However, it may be nice to have that consistency with other CI/CD platforms.
Usage in [this PR](https://github.com/go-vela/worker/pull/254)
> feat(secrets): adding logging mask constant 

- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
- .github/workflows/schema.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
- go.mod
- version/metadata_test.go
- version/version_test.go
Updates Go to 1.17, GitHub Actions pipelines included.
> chore(deps): update go to 1.17

- webhook.go
- webhook_test.go
xref: https://github.com/go-vela/community/issues/454
> enhance(webhook): enable skipping builds during tag events

- library/build.go
- library/build_test.go
- library/service.go
- library/service_test.go
- library/step.go
- library/step_test.go
Currently, we have logic to calculate the duration (amount of time a resource was running) for various resources.
The following resources have this functionality:
* [build](https://github.com/go-vela/cli/blob/master/action/build/table.go#L135-L158)
* [service](https://github.com/go-vela/cli/blob/master/action/service/table.go#L131-L154)
* [step](https://github.com/go-vela/cli/blob/master/action/step/table.go#L131-L154)
This change introduces a `Duration()` method on each of these resources that will replace the above linked functions:
https://github.com/go-vela/types/blob/16db0dbc3136fa4a3731b2dcc6c8f32271d3f5d2/library/build.go#L51-L70
https://github.com/go-vela/types/blob/16db0dbc3136fa4a3731b2dcc6c8f32271d3f5d2/library/service.go#L36-L55 …
> feat(library): add Duration() function to resources

- library/service.go
- library/service_test.go
- library/step.go
- library/step_test.go
Essentially a copy of https://github.com/go-vela/types/pull/205
This adds a `ServiceFromBuildContainer()` function to the `github.com/go-vela/types/library` package:
https://github.com/go-vela/types/blob/240fd4a9d453bc9a377e33447144dfb6602ab31a/library/service.go#L503-L528
Similar to `StepFromBuildContainer()`, that was added in the above PR, this will be used in the [go-vela/worker](https://github.com/go-vela/worker) codebase.
Also, following along with the above PR, `ServiceFromContainer` was renamed to `ServiceFromContainerEnvironment`.
> feat(library): add ServiceFromBuildContainer()

- library/log.go
- library/log_test.go
Moving the secret masking from the worker to be a method within `library.Log`. Also made it much more robust with its pattern matching with some go-regexp fun stuff.
> chore/fix(log): moving secret masking to log type

- library/build.go
- library/build_test.go
- library/service.go
- library/service_test.go
- library/step.go
- library/step_test.go
Based off feedback from https://github.com/go-vela/types/pull/222#issuecomment-1003031343
This updates the value returned from `Duration()` for resources in the `github.com/go-vela/types/library` package.
The following resources have this function:
* [build](https://github.com/go-vela/types/blob/c491e96440a50566b68980de606748ec7c469acd/library/build.go#L51-L70)
* [service](https://github.com/go-vela/types/blob/c491e96440a50566b68980de606748ec7c469acd/library/service.go#L36-L55)
* [step](https://github.com/go-vela/types/blob/c491e96440a50566b68980de606748ec7c469acd/library/step.go#L38-L57)
Previously, we were returning `0s` if the `started` or `finished` timestamps weren't set for the resource.
Now, If a resource doesn't have a `started` timestamp, then an indeterminate value of `...` is …
> enhance(library): update Duration() return values

- pipeline/metadata.go
- yaml/metadata.go
- yaml/template.go
Add support for utilizing stages within templates.
xref: https://github.com/go-vela/community/issues/233
> feat: support stages with templates

- database/repo.go
- database/repo_test.go
- library/repo.go
- library/repo_test.go
As noted [here](https://github.com/go-vela/server/pull/607#pullrequestreview-906303616), the done criteria for https://github.com/go-vela/community/issues/343 can be accomplished using a different query rather than adding a column to the database.
> revert(repo): remove last update field

- yaml/build.go
- yaml/build_test.go
- yaml/metadata.go
- yaml/metadata_test.go
- yaml/testdata/build.yml
- yaml/testdata/build_empty_env.yml
Closes https://github.com/go-vela/community/issues/514
When a user does not supply the `metadata` tag, the unmarshaling routine would not trigger the custom unmarshaler we had in place to populate the environment with the appropriate containers. By moving the custom unmarshaler, we get a broader scope and thus can check the `metadata` after it has been unmarshaled. 
By changing the slice length check to a slice nil check, files written with `metadata.Environment = []` will be processed as expected: environment will not be injected into _any_ container.
> fix(metadata): moving metadata unmarshaler override to build

- database/hook.go
- database/hook_test.go
- library/build.go
- library/hook.go
- library/hook_test.go
Couple related issues: https://github.com/go-vela/community/issues/459 and https://github.com/go-vela/community/issues/416
The `hook_id` is the field needed from GitHub to not only reach that deliveries page but also interact with any of their API endpoints related to hook deliveries. A `hook_id` is unique to any one hook within a repo, but since we already have an `id` field as well as a `repo_id` field, I chose `address` as the name. If anyone has a suggestion for another name, I am all ears! 
I also cleaned up a couple of typos I noticed in the comments of `build.go`
> feat(hook): add hook id to hook object

- constants/action.go
- database/build.go
- database/build_test.go
- library/build.go
- library/build_test.go
- library/secret.go
- yaml/ruleset.go
- yaml/ruleset_test.go
- yaml/testdata/ruleset_advanced.yml
I was noticing an issue with [my first iteration on this](https://github.com/go-vela/types/pull/236). In order to execute a step, it must pass [the purge process](https://github.com/go-vela/types/blob/abb9e3afc4bd429783c6805c051e85aa58b93652/pipeline/container.go#L60) and [the skip process](https://github.com/go-vela/worker/blob/151849034f86575046422c1407d33fc1aafa13b1/internal/step/skip.go#L18). In order to respect scoped events (`pull_request:opened` for example), I needed to change the `build.Event` value to that [here](https://github.com/go-vela/server/blob/ccfff2af42eea4abeceac8ac3d5b93790b3ef300/scm/github/webhook.go#L208). This is not ideal. Not only does it require splitting logic all over to respect various event gatekeeping, it also changes the environment variable …
> feat(rulesets): add event action field

- .gitignore
- constants/action.go
- constants/event.go
- database/hook.go
- database/hook_test.go
- library/hook.go
- library/hook_test.go
Context: there have been some errors related to repository events not being processed correctly by the webhook endpoint. This led me to look over the [renaming a repository code](https://github.com/go-vela/server/pull/556). The fix for the errors can be handled in the server code, but what caught my eye was the fact that I chose to override the `hook.Event` field to be a custom `renameRepository` hard-coded string. With the [new scoped ruleset support](https://github.com/go-vela/server/pull/630), I think it would be consistent to mirror `build.Event` and `build.EventAction` with `hook.Event` and `hook.EventAction`. 
Also random, but VSCode tried to include a project folder in the commit, so I added that to the `.gitignore`.
> fix(hook): clean up old repo rename code by adding action field to hook

- constants/action.go
- yaml/build_test.go
- yaml/ruleset.go
- yaml/ruleset_test.go
- yaml/testdata/build.yml
Since we decided to model off of what GH tells us is the action, I forgot to change this one instance of unmarshaling where I used `synchronized` instead of `synchronize`.
> fix(yaml/ruleset): fix unmarshal PR event to use synchronize, not synchronized

- cmd/schema/main.go
One letter change. `Synchronize` is the action specified in the GH webhook payload, so we decided to mirror that in the code.
> fix(schema): synchronized to synchronize in order to mirror GH

- database/compression.go
- raw/map_test.go
- raw/slice_test.go
- yaml/build_test.go
- yaml/ruleset_test.go
- yaml/secret_test.go
- yaml/service_test.go
- yaml/stage_test.go
- yaml/step_test.go
- yaml/template_test.go
- yaml/ulimit_test.go
- yaml/volume_test.go
I noticed that the `io/ioutil` package has been deprecated since Go 1.16 (see [here](https://pkg.go.dev/io/ioutil) for details). Luckily it seems the functions we were using have 1-to-1 connections to supported functions in the `io` and `os` packages.
> chore(io/os): change ioutil to io or os pkg due to deprecation

- constants/doc.go
- database/doc.go
- library/doc.go
- library/repo.go
- pipeline/build.go
- pipeline/container.go
- pipeline/doc.go
- pipeline/stage.go
- raw/doc.go
- version/doc.go
- yaml/doc.go
Linter was complaining about several files not having `gofmt -s` run against them. Seems like it changed some bullets and spacing.
> chore(lint): ran gofmt -s on all files

- .github/workflows/reviewdog.yml
- .github/workflows/schema.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
waiting for https://github.com/actions/go-versions/pull/60 to get merged to pull in 1.19.2 instead of 1.19.1 because that's what check_latest looks at to get the newest version.
I validated that this is need by rerunning https://github.com/go-vela/types/actions/runs/3171645351/jobs/5232434827 after the fix above was merged. It still pulled in the cached 1.19.1 version of Go.
We will want to apply this to all repos :octocat: (EDIT: ✅ PRs have been created)
> fix(actions): make sure to use latest Go version

- constants/limit.go
- database/repo.go
- database/repo_test.go
- library/repo.go
- library/repo_test.go
Part of the effort for https://github.com/go-vela/community/issues/774
Injects repo topics into the environment as well as saves them in the database.
> enhance(repo): add repo topics to repo object + build environment

- go.mod
- go.sum
- pipeline/container.go
Reverting https://github.com/go-vela/types/pull/284 due to reason in title
> revert(envsubst): rolling back upgrade to envsubst library due to errors in handling multiline json keys

- cmd/schema/main.go
fixes an issue when using rulesets that match both the normal and the "flattened" props.
provide the schema to [VSCode YAML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) (or use `Yaml › Schema Store: Enable`) and use the following pipeline syntax:
```yaml
version: "1"
steps:
- name: anything
image: golang
ruleset:
continue: true
commands:
- "echo hello"
```
the `continue` tag within `ruleset` will match both objects provided in the `Ruleset` block based on the `oneOf` matcher.
error:
```
Matches multiple schemas when only one must validate.yaml-schema: Vela Pipeline Configuration
```
*Note*: im not sure if the bug exists for the other blocks using `oneOf`, i just see the error in `ruleset` because i apply continues when debugging.
> fix(schema): use anyOf for ruleset matching

- constants/event.go
- constants/table.go
- database/schedule.go
- database/schedule_test.go
- go.mod
- go.sum
- library/schedule.go
- library/schedule_test.go
- pipeline/ruleset.go
- pipeline/ruleset_test.go
- yaml/ruleset.go
- yaml/ruleset_test.go
- yaml/testdata/ruleset_advanced.yml
xref: https://github.com/go-vela/community/issues/538
Part of https://github.com/go-vela/community/pull/772
This adds a new `schedule` event type which will be used in [go-vela/server](https://github.com/go-vela/server).
This also adds some test cases for `ruleset` in the `pipeline` and `yaml` packages.
Additionally, this adds a new `Schedule{}` type to the `github.com/go-vela/types/database` package:
https://github.com/go-vela/types/blob/cb989d14b504dec068fde6618bc02116fd0996d7/database/schedule.go#L29-L41
And adds a new `Schedule{}` type to the `github.com/go-vela/types/library` package:
https://github.com/go-vela/types/blob/cb989d14b504dec068fde6618bc02116fd0996d7/library/schedule.go#L11-L25
These will be used in the [go-vela/server](https://github.com/go-vela/server) to create a new …
> feat: add support for schedules

- database/repo.go
- database/repo_test.go
- library/repo.go
- library/repo_test.go
Reverts go-vela/types#291 based off of https://github.com/go-vela/types/pull/291#issuecomment-1554711054
> revert(repo): add AllowSchedule field

- item.go
- item_test.go
Part of https://github.com/go-vela/community/issues/811
Blocks: https://github.com/go-vela/worker/pull/478
This adds an `ItemVersion` field to `Item` with an `ItemVersion` constant  that should be bumped whenever we make significant changes to `Item` or the `pipeline.Build`. This way, the worker can detect any stale builds that were queued before a Vela server upgrade or downgrade, and fail the build.
In the future, we could do something even nicer and ask the server to recompile and requeue the build.
> feat!: protect against stale queue items

- library/log.go
- library/log_test.go
Adding `?` and `&` to masking buffer and adding a test. Extra layer of protection.
> enhance(log): improve secret masking to better handle URL strings

- database/build_executable.go
- database/build_executable_test.go
Ref: https://github.com/go-vela/server/pull/927#discussion_r1297772714
Rows will include sensitive information, so it is best to encrypt the data.
> enhance(executable): encrypt DB executable

- library/secret.go
- library/secret_test.go
Secrets were not able to work for schedule events because they weren't passing the `Match` check for injection into containers.
I also decided to discontinue our use of `BUILD_EVENT` as it has been deprecated in favor of `VELA_BUILD_EVENT`
> fix(secrets): support schedule event

- library/secret.go
- library/secret_test.go
Preparing patch release for `v0.20.2` with these changes: https://github.com/go-vela/types/pull/308
> patch(v0.20.2/secrets): allow schedule event type

- constants/action.go
- yaml/build_test.go
- yaml/ruleset.go
- yaml/ruleset_test.go
Found a bug (?) where users were expecting a Vela pull request build to launch when they re-opened a pull request, much like there is one when a user opens a pull request. 
If we are to support `reopened` as a pull_request action, I believe it should also be a default in this custom unmarshal value for `pull_request`.
> fix(yaml): add reopened action to default pull_request unmarshal

- library/log.go
- library/log_test.go
Had a case where the verbose flag in a cURL request logged a secret by accident. Adding some brackets to the mask buffer
> fix(log): add brackets to secret mask

- constants/allow_events.go
- library/actions/pull.go
- library/actions/pull_test.go
- library/actions/push_test.go
- library/events_test.go
- yaml/ruleset.go
While I was working on the original PR for this new allow_events remodel, we added support for the [reopening action](https://github.com/go-vela/server/pull/1002).
> fix(repo_events): add support for reopen

- constants/allow_events.go
- database/secret.go
- database/secret_test.go
- library/actions/comment.go
- library/actions/push.go
- library/actions/push_test.go
- library/actions/schedule.go
- library/actions/schedule_test.go
- library/events.go
- library/events_test.go
- library/repo.go
- library/repo_test.go
- library/secret.go
- library/secret_test.go
It will be helpful to share the same structure for allowed events for both repos and secrets.
> enhance(secret): use allow event system

- library/events.go
Goes along with this PR: [https://github.com/go-vela/types/pull/340](https://github.com/go-vela/types/pull/340)
Adding a last piece to enable delete events.
> fix: enabling a delete event to be allowed

- library/events.go
- library/repo.go
This got moved to be a method for the `Events` struct in this PR: https://github.com/go-vela/types/pull/341
> fix(repo): remove dead code EventAllowed

- .github/workflows/pr-title-validate.yml
Curious what the thoughts are on something like this. I know we use a [script](https://github.com/go-vela/community/blob/main/releases/scripts/relgen.sh) to generate release notes that relies on this pattern.
> enhance(ci): include PR title validation workflow

- library/events.go
- library/events_test.go
- library/repo_test.go
Hopefully these tests will prevent small cases like this in the future.
> fix(events): add schedule to ToDatabase and improve tests

- .github/workflows/pr-title-validate.yml
According to our [docs](https://go-vela.github.io/docs/community/contributing_guidelines/#development-workflow), we should accept both formats:
Scope:
- feat(scope): cool thing
No Scope:
- feat: scope-less cool thing
> fix: title validator handle no parentheses + enforce whitespace

- database/build.go
- database/build_test.go
Forgot to change Deploy to DeployNumber when adding DeployNumber field to Build, fixing that here
> fix: fixing Nullify() DeployNumber statment to actually work

- constants/limit.go
- database/deployment.go
- database/deployment_test.go
Adding a limit + an eviction policy so we prioritize most recent builds for a given deployment.
> fix(database): add limit and eviction policy for deployment builds

- .github/workflows/codeql-analysis.yml
- .github/workflows/reviewdog.yml
- .github/workflows/schema.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
This _should_ make renovate update minor/patch versions in the comment whenever the SHA is updated.
> chore(ci): include minor and patch versions in workflows

- constants/action.go
- constants/event.go
- library/events.go
- library/events_test.go
This will allow for the CLI and Server and any other user code to more easily generate the `AllowEvents` struct from a common source of input (a slice).
> enhance(events): add NewEventsFromSlice method

- constants/limit.go
- database/step.go
- database/step_test.go
- library/step.go
- library/step_test.go
- pipeline/container.go
- pipeline/container_test.go
- yaml/step.go
- yaml/step_test.go
- yaml/testdata/step.yml
Ref: https://github.com/go-vela/community/issues/576
Also fixes bug noted in https://github.com/go-vela/community/issues/958 by setting the ground work to _not_ report on the `pull_request` context when the action type is non-standard (opened, reopened, synchronize). Solving bugs with features!
This also lays some groundwork for potential usage of the checks API whenever Vela implements GitHub App integration
Server PR, in draft form, which may be more of interest: https://github.com/go-vela/server/pull/1090
> feat: allow for step status reporting to SCM as its own context

- database/repo.go
- database/repo_test.go
- database/secret.go
- database/secret_test.go
- item_test.go
- library/repo.go
- library/repo_test.go
- library/secret.go
- library/secret_test.go
`v0.23` kept these fields around in case of need for reverting. With `v0.24` slotted as our next release, we can pursue removing these unused fields
> chore: delete legacy allow event fields and methods

- library/events.go
- library/events_test.go
make it easier to err check invalid events elsewhere
> enhance: return err in NewEventsFromSlice

- .github/workflows/validate.yml
- .golangci.yml
- Makefile
- database/deployment.go
- database/deployment_test.go
- database/repo.go
- database/schedule.go
- database/secret.go
- database/user.go
- database/worker.go
- go.mod
- library/actions/pull.go
- library/actions/push.go
- library/build_test.go
- library/events_test.go
- library/repo.go
- library/repo_test.go
- library/secret_test.go
- yaml/build_test.go
- yaml/ruleset_test.go
- yaml/secret_test.go
- yaml/service_test.go
- yaml/stage.go
- yaml/stage_test.go
- yaml/step_test.go
- yaml/template_test.go
- yaml/ulimit_test.go
- yaml/volume_test.go
to match https://github.com/go-vela/server/pull/1077, https://github.com/go-vela/server/pull/1101
> chore: pin go version; import order; linter setup

- library/events.go
- library/events_test.go
- library/repo.go
- library/secret.go
lets `allow_events` be unmarshalled as a string slice in yaml, primarily for the cli to read add/update input from a file.
kudos @wsan3 for spotting the bug
> fix: allow events yaml unmarshal

- .github/workflows/pr-title-validate.yml
We have workflow approval settings properly configured, but this is best practice.
See: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
> fix(ci): use intermediate env variable for PR title validator

- pipeline/container.go
- pipeline/container_test.go
- yaml/step.go
- yaml/step_test.go
The majority of this code will be in the server, and there is a branch with the same name there that has the implementation if anyone is curious.
For types specifically, I don't think `VELA_ID_TOKEN_REQUEST_TOKEN`s should be available in _all_ steps. Users should be able to specifically invoke the injection of the token using something like:
```yaml
version: "1"
steps:
- name: request token
image: alpine:latest
id_request: write  # becomes a claim in token `request`
commands:
- apk add curl
- 'curl -H "Authorization: Bearer $VELA_ID_TOKEN_REQUEST_TOKEN" $VELA_ID_TOKEN_REQUEST_URL'
```
The string value for `id_request` just becomes one of the claims in the eventual ID token. I figured that may be useful in some contexts.
> feat: Vela OIDC Provider

- pipeline/container.go
- pipeline/container_test.go
Add `label` as another rule to skip when matching during container execution, as worker lacks necessary rule data.
The compiler already determines whether a container will run based on that rule and others.
> fix(container): skip "label" rule evaluation in container execution

- library/build.go
- library/build_queue.go
- library/executor.go
- library/repo.go
- library/schedule.go
- library/user.go
- library/worker.go
the modified model annotations have moved to [go-vela/server/api/types](https://github.com/go-vela/server/blob/main/api/types) where a duplicate of these annotations can be found. this change is needed for accurate swagger doc generation. see
https://github.com/go-vela/server/pull/1159 .
i've replaced the swagger documentation with godoc annotation that marks these structs as deprecated, so we should see warnings anywhere these are used yet.
> fix(swagger): remove old model annotations

- yaml/build_test.go
- yaml/secret.go
- yaml/secret_test.go
Since we [already inject secrets in uppercase no matter what](https://github.com/go-vela/worker/blob/dd70412c168c4fc137490d01354991e3cc3d4380/executor/linux/secret.go#L352), we might as well be honest during parsing and capitalize the secret `target`
> enhance(secrets): uppercase secret target

- go.mod
- go.sum
- library/string.go
- raw/map_test.go
- raw/slice_test.go
- yaml/build_test.go
- yaml/ruleset_test.go
- yaml/secret_test.go
- yaml/service_test.go
- yaml/stage.go
- yaml/stage_test.go
- yaml/step_test.go
- yaml/template_test.go
- yaml/ulimit_test.go
- yaml/volume_test.go
Use `yaml.Node` to create our own `MapSlice` type that we were relying on with the buildkite/go-yamlV2 implementation. However, now anchors will work with stages, as is made obvious by the passing tests that came from https://github.com/go-vela/types/pull/12.
> fix(yaml): remediate insecure/archived buildkite lib in favor of go-yaml v3

- go.mod
- go.sum
- library/string.go
- raw/map_test.go
- raw/slice_test.go
- yaml/build_test.go
- yaml/ruleset_test.go
- yaml/secret_test.go
- yaml/service_test.go
- yaml/stage.go
- yaml/stage_test.go
- yaml/step_test.go
- yaml/template_test.go
- yaml/testdata/merge_anchor.yml
- yaml/ulimit_test.go
- yaml/volume_test.go
Due to the breaking changes in `v3` and the accelerated timeline of getting `v0.25.0` out the door, our YAML library change will occur in `v0.26`
Additional context: https://github.com/go-vela/types/pull/391
> fix(revert): use buildkite as yaml parser
